import { Poppins } from "next/font/google";
import "../globals.css";
import React from "react";
import ProvidersWrapper from "@/component/providers/ProviderWappers";

const poppins = Poppins({
    subsets: ["latin"],
    variable: "--font-poppins",
    weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${poppins.variable} antialiased` }  cz-shortcut-listen="true" >
            <ProvidersWrapper>
                {children}
            </ProvidersWrapper>
        </body>
        </html>
    );
}
