import {createSlice} from "@reduxjs/toolkit";

export const DataListSlice = createSlice({
    name: 'DataList',
    initialState: {
        data : [
            {
                id: 1,
                title: 'Carolina',
                description: 'Classic Carolina style t-shirt',
                price: 150,
                discountPrice: 50,
                size: ['sm', 'md', 'lg', 'xl'],
                colors: ['red', 'green', 'yellow', 'blue'],
                qty: '4',
                season: 'summer',
                category: 't-shirt',
                image: ['Carolina1.jpg', 'Carolina2.jpg', 'Carolina3.jpg'],
                rating: '4'
            },
            {
                id: 2,
                title: 'Urban Vibe',
                description: 'Trendy urban streetwear t-shirt',
                price: 170,
                discountPrice: 50,
                size: ['sm', 'md', 'lg'],
                colors: ['black', 'white'],
                qty: '10',
                season: 'summer',
                category: 't-shirt',
                image: ['Urban1.jpg', 'Urban2.jpg', 'Urban3.jpg'],
                rating: '4.5'
            },
            {
                id: 3,
                title: 'Classic Fit',
                description: 'Comfortable everyday wear shirt',
                price: 120,
                discountPrice: 30,
                size: ['md', 'lg', 'xl'],
                colors: ['navy', 'gray'],
                qty: '6',
                season: 'spring',
                category: 'shirt',
                image: ['Classic1.jpg', 'Classic2.jpg', 'Classic3.jpg'],
                rating: '4'
            },
            {
                id: 4,
                title: 'Beach Vibes',
                description: 'Lightweight summer t-shirt',
                price: 140,
                discountPrice: 40,
                size: ['sm', 'md'],
                colors: ['sky blue', 'white', 'yellow'],
                qty: '8',
                season: 'summer',
                category: 't-shirt',
                image: ['Beach1.jpg', 'Beach2.jpg', 'Beach3.jpg'],
                rating: '4.2'
            },
            {
                id: 5,
                title: 'Monochrome',
                description: 'Minimal black and white style shirt',
                price: 160,
                discountPrice: 35,
                size: ['md', 'lg', 'xl'],
                colors: ['black', 'white'],
                qty: '7',
                season: 'autumn',
                category: 'shirt',
                image: ['Mono1.jpg', 'Mono2.jpg', 'Mono3.jpg'],
                rating: '3.9'
            },
            {
                id: 6,
                title: 'SportX',
                description: 'Perfect for sports and workouts',
                price: 180,
                discountPrice: 50,
                size: ['sm', 'md', 'lg'],
                colors: ['red', 'blue'],
                qty: '12',
                season: 'all',
                category: 't-shirt',
                image: ['Sport1.jpg', 'Sport2.jpg', 'Sport3.jpg'],
                rating: '4.7'
            },
            {
                id: 7,
                title: 'Winter Shield',
                description: 'Heavy blazer for cold weather',
                price: 350,
                discountPrice: 70,
                size: ['lg', 'xl'],
                colors: ['black', 'navy'],
                qty: '3',
                season: 'winter',
                category: 'blazer',
                image: ['Blazer1.jpg', 'Blazer2.jpg', 'Blazer3.jpg'],
                rating: '4.6'
            },
            {
                id: 8,
                title: 'Casual Friday',
                description: 'Relaxed style office shirt',
                price: 210,
                discountPrice: 60,
                size: ['md', 'lg'],
                colors: ['gray', 'white'],
                qty: '9',
                season: 'spring',
                category: 'shirt',
                image: ['Friday1.jpg', 'Friday2.jpg', 'Friday3.jpg'],
                rating: '4.1'
            },
            {
                id: 9,
                title: 'Denim Pro',
                description: 'Stylish denim pants',
                price: 250,
                discountPrice: 45,
                size: ['sm', 'md', 'lg'],
                colors: ['blue', 'black'],
                qty: '5',
                season: 'all',
                category: 'pant',
                image: ['Denim1.jpg', 'Denim2.jpg', 'Denim3.jpg'],
                rating: '4.3'
            },
            {
                id: 10,
                title: 'Vintage Cotton',
                description: 'Soft vintage cotton t-shirt',
                price: 155,
                discountPrice: 50,
                size: ['sm', 'md', 'lg', 'xl'],
                colors: ['brown', 'beige'],
                qty: '5',
                season: 'summer',
                category: 't-shirt',
                image: ['Vintage1.jpg', 'Vintage2.jpg', 'Vintage3.jpg'],
                rating: '4.3'
            },
            {
                id: 11,
                title: 'Bold Print',
                description: 'Bold graphics for bold statements',
                price: 190,
                discountPrice: 50,
                size: ['md', 'lg'],
                colors: ['black', 'orange'],
                qty: '9',
                season: 'summer',
                category: 't-shirt',
                image: ['Bold1.jpg', 'Bold2.jpg', 'Bold3.jpg'],
                rating: '4.6'
            },
            {
                id: 12,
                title: 'EcoFlex',
                description: 'Eco-friendly stretch cotton t-shirt',
                price: 200,
                discountPrice: 50,
                size: ['sm', 'md', 'lg'],
                colors: ['green', 'white'],
                qty: '4',
                season: 'summer',
                category: 't-shirt',
                image: ['Eco1.jpg', 'Eco2.jpg', 'Eco3.jpg'],
                rating: '4.8'
            },
            {
                id: 13,
                title: 'Winter Classic',
                description: 'Warm and cozy woolen blazer',
                price: 400,
                discountPrice: 100,
                size: ['lg', 'xl'],
                colors: ['maroon', 'black'],
                qty: '4',
                season: 'winter',
                category: 'blazer',
                image: ['Winter1.jpg', 'Winter2.jpg', 'Winter3.jpg'],
                rating: '4.9'
            },
            {
                id: 14,
                title: 'Logo Tee',
                description: 'Logo printed branded t-shirt',
                price: 220,
                discountPrice: 50,
                size: ['sm', 'md', 'lg', 'xl'],
                colors: ['gray', 'black'],
                qty: '11',
                season: 'summer',
                category: 't-shirt',
                image: ['Logo1.jpg', 'Logo2.jpg', 'Logo3.jpg'],
                rating: '4.6'
            },
            {
                id: 15,
                title: 'Urban Camo',
                description: 'Urban camouflage pattern tee',
                price: 190,
                discountPrice: 50,
                size: ['sm', 'md', 'lg'],
                colors: ['camouflage'],
                qty: '5',
                season: 'autumn',
                category: 't-shirt',
                image: ['Camo1.jpg', 'Camo2.jpg', 'Camo3.jpg'],
                rating: '4.4'
            },
            {
                id: 16,
                title: 'Stretch Pants',
                description: 'Flexible stretchable pants',
                price: 240,
                discountPrice: 60,
                size: ['md', 'lg', 'xl'],
                colors: ['black', 'gray'],
                qty: '7',
                season: 'spring',
                category: 'pant',
                image: ['Stretch1.jpg', 'Stretch2.jpg', 'Stretch3.jpg'],
                rating: '4.2'
            },
            {
                id: 17,
                title: 'Soft Stripe',
                description: 'Striped casual wear t-shirt',
                price: 150,
                discountPrice: 50,
                size: ['md', 'lg'],
                colors: ['white', 'blue'],
                qty: '10',
                season: 'summer',
                category: 't-shirt',
                image: ['Stripe1.jpg', 'Stripe2.jpg', 'Stripe3.jpg'],
                rating: '4.2'
            },
            {
                id: 18,
                title: 'Formal Blue Shirt',
                description: 'Perfect for office wear',
                price: 260,
                discountPrice: 65,
                size: ['sm', 'md', 'lg'],
                colors: ['light blue', 'white'],
                qty: '6',
                season: 'autumn',
                category: 'shirt',
                image: ['Office1.jpg', 'Office2.jpg', 'Office3.jpg'],
                rating: '4.4'
            },
            {
                id: 19,
                title: 'RainGuard Blazer',
                description: 'Water-resistant blazer for rainy days',
                price: 380,
                discountPrice: 90,
                size: ['md', 'lg'],
                colors: ['gray', 'dark blue'],
                qty: '4',
                season: 'rainy',
                category: 'blazer',
                image: ['Rain1.jpg', 'Rain2.jpg', 'Rain3.jpg'],
                rating: '4.5'
            },
            {
                id: 20,
                title: 'Basic Tee',
                description: 'Affordable everyday t-shirt',
                price: 100,
                discountPrice: 50,
                size: ['sm', 'md', 'lg'],
                colors: ['white', 'black'],
                qty: '15',
                season: 'summer',
                category: 't-shirt',
                image: ['Basic1.jpg', 'Basic2.jpg', 'Basic3.jpg'],
                rating: '4.0'
            },{
                id: 20,
                title: 'Basic Tee',
                description: 'Affordable everyday t-shirt',
                price: 100,
                discountPrice: 50,
                size: ['sm', 'md', 'lg'],
                colors: ['white', 'black'],
                qty: '15',
                season: 'summer',
                category: 'panjabi',
                image: ['Basic1.jpg', 'Basic2.jpg', 'Basic3.jpg'],
                rating: '4.0'
            }
        ]
    },

    reducers: {

    }
})


export default DataListSlice.reducer;